#include <stdlib.h>
#include <stdio.h>


static int add(int a, int b) {
    abort();
    return a + b;
}

static int add_wrapper(int a, int b) {
    printf("a: %d\n", a);
    printf("b: %d\n", b);
    return add(a,b);
}
int main(void) {
    printf("Hello");
    add_wrapper(1,2);
}

/*
> ulimit -c unlimited
> gcc abort_get_coredump.c
> ulimit -c unlimited
> ./a.out
Helloa: 1
b: 2
Aborted (core dumped)
> ls
abort_get_coredump.c  a.out  core
> gdb a.out  core
GNU gdb (GDB; SUSE Linux Enterprise 12) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...

warning: /etc/gdbinit.d/gdb-heap.py: No such file or directory
Reading symbols from a.out...done.
[New LWP 20382]
Core was generated by `./a.out'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fcd26cac187 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.19-17.72.emc4975661.4975661.x86_64
(gdb) bt
#0  0x00007fcd26cac187 in raise () from /lib64/libc.so.6
#1  0x00007fcd26cad538 in abort () from /lib64/libc.so.6
#2  0x00000000004005b0 in add (a=1, b=2) at abort_get_coredump.c:6
#3  0x00000000004005f5 in add_wrapper (a=1, b=2) at abort_get_coredump.c:13
#4  0x0000000000400619 in main () at abort_get_coredump.c:17
(gdb)

 */
